// src/components/chapter-two/PhotographyWall.vue
<template>
  <!-- overflow-x: clip, not hidden — hidden would make this a scroll
       container and break sticky measurements elsewhere on the page. -->
  <section id="photos" class="wall" aria-label="Photography">
    <div class="container">
      <SectionHeader
        note="chasing light…"
        title="Photography"
        highlight="Photography"
        hue="blue"
        :handle="photoMeta.handle"
        :handle-href="photoMeta.profileUrl"
        :vis="vis"
      />
    </div>

    <!--
      CSS columns rather than absolute coordinates: the frames keep their
      overlap and varied depth without a fixed scatter that would tear apart
      if any card's height changed. Single column below md.
    -->
    <div ref="group" class="container wall__grid pinned-group" :class="{ 'is-in': vis }">
      <div
        v-for="(photo, i) in photos"
        :key="photo.id"
        class="wall__cell"
        :style="{
          marginTop: OFFSETS[i % OFFSETS.length],
          marginLeft: i % 3 === 1 ? '-0.75rem' : undefined,
        }"
      >
        <Pinned :tilt="photo.rotate" :index="i" inner-class="polaroid">
          <span
            class="tape"
            :class="i % 2 === 0 ? 'polaroid__tape--l' : 'polaroid__tape--r'"
            :style="{ '--tape-hue': `var(--crayon-${HUES[i % HUES.length]})`, rotate: `${i % 2 === 0 ? -8 : 9}deg` }"
          ></span>

          <a :href="photo.href" target="_blank" rel="noopener" class="polaroid__frame">
            <img v-if="photo.src" :src="photo.src" :alt="photo.caption" loading="lazy" />
            <FilmFrame v-else :index="i + 1" :total="photos.length" />
            <span class="polaroid__cta hand">View on Instagram ↗</span>
          </a>

          <!-- Contact-sheet index — the only caption the frame carries. -->
          <span class="polaroid__idx hand">{{ String(i + 1).padStart(2, '0') }}</span>
        </Pinned>
      </div>
    </div>

    <div class="container wall__out">
      <a :href="photoMeta.profileUrl" target="_blank" rel="noopener" class="wall__link hand">
        more frames on Instagram ↗
      </a>
    </div>
  </section>
</template>

<script setup lang="ts">
import { photographyWall as photos, photographyMeta as photoMeta } from '../../content/novel';
import SectionHeader from './SectionHeader.vue';
import FilmFrame from './FilmFrame.vue';
import Pinned from './Pinned.vue';

defineProps<{ vis?: boolean }>();

/* One hue per frame across the wall. */
const HUES = ['blue', 'sun', 'pink', 'leaf', 'peach', 'violet'];

/* Per-card vertical offset — breaks the column baselines so the wall reads
   as pinned by hand rather than laid out on a grid. */
const OFFSETS = ['0', '2.5rem', '1rem', '3.5rem', '1.5rem', '0.5rem'];
</script>

<style scoped>
.wall {
  overflow-x: clip;
  padding: var(--sp-9) 0 0;
  margin-top: var(--sp-8);
  border-top: 1px solid var(--border);
}

.wall__grid {
  margin-top: var(--sp-8);
  columns: 1;
}
@media (min-width: 760px)  { .wall__grid { columns: 2; column-gap: var(--sp-7); } }
@media (min-width: 1080px) { .wall__grid { columns: 3; column-gap: var(--sp-6); } }

.wall__cell {
  break-inside: avoid;
  margin-bottom: var(--sp-7);
}
/* The hand-placed offsets only make sense once there are columns to break. */
@media (max-width: 759px) {
  .wall__cell { margin-top: 0 !important; margin-left: 0 !important; }
}

.polaroid {
  border-radius: 3px;
  border: 1px solid var(--border);
  background: var(--surface-solid);
  /* Deep bottom lip — the polaroid chin. */
  padding: 8px 8px 34px;
}

.polaroid__tape--l { top: -12px; left: 1.75rem; }
.polaroid__tape--r { top: -12px; right: 1.75rem; }

.polaroid__frame {
  position: relative;
  display: block;
  aspect-ratio: 1;
  overflow: hidden;
  background: var(--surface-2);
}
.polaroid__frame img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  display: block;
}
.polaroid__cta {
  position: absolute;
  inset: 0;
  display: grid;
  place-items: center;
  font-size: 1.25rem;
  color: var(--caption-color);
  background: var(--scrim);
  opacity: 0;
  transition: opacity 300ms var(--ease-out);
}
.polaroid__frame:hover .polaroid__cta,
.polaroid__frame:focus-visible .polaroid__cta { opacity: 1; }

.polaroid__idx {
  position: absolute;
  right: 0.9rem;
  bottom: 0.15rem;
  font-size: 1.15rem;
  color: var(--text-muted);
}

.wall__out { text-align: center; margin-top: var(--sp-6); }
.wall__link {
  font-size: 1.35rem;
  color: var(--text-muted);
  text-decoration: underline;
  text-decoration-color: var(--crayon-blue);
  text-decoration-thickness: 2px;
  text-underline-offset: 6px;
  transition: color 240ms var(--ease-out);
}
.wall__link:hover { color: var(--text); }
</style>

// components/novel/chapter-two/PhotographyWall.tsx
"use client";

import { Reveal } from "../Reveal";
import { SectionHeader } from "./SectionHeader";
import { LazyInstagram } from "./LazyInstagram";
import { Pinned, PinnedGroup, Tape, type CrayonHue } from "./Pinboard";
import { photographyWall, photographyMeta } from "@/content/novel";

/*
 * Photography — the posts as a wall of polaroids rather than a carousel.
 *
 * Laid out in CSS columns, not absolute coordinates: Meta's embed script
 * rewrites each blockquote's height after it loads, which would tear a
 * fixed-position scatter apart. Columns keep the overlap and the varied
 * depth while surviving that reflow. Below `md` the wall becomes a single
 * column — Instagram's embed has a 326px minimum width and will overflow
 * anything narrower.
 */

/* Each tape a different hue across the wall (DESIGN.md application rule 4). */
const TAPE_HUES: CrayonHue[] = ["blue", "sun", "pink", "leaf", "peach", "violet"];

/* Per-card vertical offset — breaks the column baselines so the wall reads
   as pinned by hand rather than laid out on a grid. */
const OFFSETS = ["md:mt-0", "md:mt-10", "md:mt-4", "md:mt-14", "md:mt-6", "md:mt-2"];

export function PhotographyWall() {
  return (
    /* overflow-x-clip, not hidden: clip leaves the vertical axis alone,
       where `hidden` would turn the section into a scroll container and
       break the sticky/ScrollTrigger measurements above it. */
    <section aria-label="Photography" className="overflow-x-clip py-16 md:py-24">
      <SectionHeader
        note="chasing light…"
        title="Photography"
        highlight="Photography"
        hue="blue"
        handle={photographyMeta.handle}
        handleHref={photographyMeta.profileUrl}
      />

      {/* Tight gutters below sm: Instagram's embed will not render under
          326px wide, and px-6 plus card padding leaves less than that on a
          390px phone. */}
      <PinnedGroup className="mx-auto mt-16 max-w-6xl px-2 sm:px-6 md:mt-20 md:columns-2 md:gap-10 lg:columns-3 lg:gap-8">
        {photographyWall.map((photo, i) => (
          <div
            key={photo.id}
            className={`mb-10 break-inside-avoid ${OFFSETS[i % OFFSETS.length]}`}
            /* Alternating pull-in creates the overlap between columns. */
            style={{ marginLeft: i % 3 === 1 ? "-0.75rem" : undefined }}
          >
            <Pinned
              tilt={photo.rotate}
              className="border border-border bg-surface p-1.5 pb-8 sm:p-2 sm:pb-8"
            >
              <Tape
                hue={TAPE_HUES[i % TAPE_HUES.length]}
                className={i % 2 === 0 ? "-top-3 left-7" : "-top-3 right-7"}
                rotate={i % 2 === 0 ? -8 : 9}
              />
              <LazyInstagram
                href={photo.href}
                hue="blue"
                aspect="aspect-square"
                label="View on Instagram ↗"
              />
              {/* Contact-sheet index — the only caption; the embed carries
                  the real one from the post itself. */}
              <span className="type-hand absolute bottom-1 right-3 text-lg text-text-muted">
                {String(i + 1).padStart(2, "0")}
              </span>
            </Pinned>
          </div>
        ))}
      </PinnedGroup>

      <Reveal className="mx-auto mt-6 max-w-6xl px-6 text-center">
        <a
          href={photographyMeta.profileUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="type-hand text-xl text-text-muted underline decoration-[var(--crayon-blue)] decoration-2 underline-offset-[6px] transition-colors duration-[var(--dur-ui)] hover:text-text"
        >
          more frames on Instagram ↗
        </a>
      </Reveal>
    </section>
  );
}
