// src/components/hero/XRayHero.vue
<template>
  <!-- Loop 2: structure only. The artistic layer sits at opacity .35 with NO
       mask so registration is checkable with the naked eye. The lens arrives
       in Loop 3; the ink spill in Loop 4. -->
  <section ref="heroRef" class="hero" data-lens>
    <!--
      REGISTRATION IS THE WHOLE TRICK, so both layers come out of ONE template.
      A second hand-written layer would drift the first time someone edits one
      side and not the other. Every box below is sized from custom properties
      declared once on .hero — no layer may hardcode a geometry value.
    -->
    <div
      v-for="layer in layers"
      :key="layer.variant"
      class="hero__layer"
      :class="`hero__layer--${layer.variant}`"
      :aria-hidden="layer.variant === 'art' || undefined"
      :inert="layer.variant === 'art' || undefined"
    >
      <div class="hero__stack">
        <p class="hero__eyebrow">{{ layer.copy.eyebrow }}</p>

        <h1 v-if="layer.variant === 'pro'" class="hero__title">{{ layer.copy.title }}</h1>
        <!-- The artistic twin is a <p>, not an <h1>: two h1s in one section is a
             document-outline bug even when one of them is aria-hidden. -->
        <p v-else class="hero__title">{{ layer.copy.title }}</p>

        <p class="hero__lead">{{ layer.copy.lead }}</p>

        <div class="hero__actions">
          <a v-if="layer.variant === 'pro'" class="hero__cta" href="#projects">
            {{ layer.copy.action }}
          </a>
          <!-- Decorative twin. Holds the slot open so the layers stay
               registered; inert, so it can never take focus. -->
          <span v-else class="hero__cta hero__cta--ghost">{{ layer.copy.action }}</span>
        </div>

        <ul class="hero__tags">
          <li v-for="tag in heroTags" :key="tag.label">
            <span class="hero__tag-label">{{ tag.label }}</span>
            <span class="hero__tag-detail">{{ tag.detail }}</span>
          </li>
          <li>
            <RouterLink v-if="layer.variant === 'pro'" class="hero__chapter-link" to="/creator">
              Chapter Two — the other half
            </RouterLink>
            <span v-else class="hero__chapter-link">Chapter Two — the other half</span>
          </li>
        </ul>
      </div>
    </div>

    <div class="hero__lens-ui" aria-hidden="true">
      <!-- The ring sits at the TRUE pointer position while the reveal below it
           lerps behind. That lag is the whole feel: a lens being dragged, not a
           CSS variable being assigned. -->
      <div ref="ringRef" class="hero__ring"></div>
    </div>

    <!-- Path B from docs/xray-plan.md section 9. The circle's radial fill IS
         the 3-stop feather; only cx/cy/r change per frame. -->
    <svg class="hero__defs" aria-hidden="true" focusable="false">
      <defs>
        <radialGradient id="xray-feather">
          <stop offset="0" stop-color="#fff" stop-opacity="1" />
          <stop offset="0.62" stop-color="#fff" stop-opacity="1" />
          <stop offset="0.82" stop-color="#fff" stop-opacity="0.4" />
          <stop offset="1" stop-color="#fff" stop-opacity="0" />
        </radialGradient>
        <mask id="xray-lens" maskUnits="userSpaceOnUse">
          <circle ref="circleRef" cx="-9999" cy="-9999" r="0" fill="url(#xray-feather)" />
        </mask>
      </defs>
    </svg>
  </section>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';
import { RouterLink } from 'vue-router';
import { heroPro, heroArt, heroTags } from '../../content/xray';

const heroRef = ref<HTMLElement | null>(null);
const circleRef = ref<SVGCircleElement | null>(null);
const ringRef = ref<HTMLElement | null>(null);

const layers = [
  { variant: 'pro' as const, copy: heroPro },
  { variant: 'art' as const, copy: heroArt },
];

/* Tuning. POS_LERP is the reveal's lag behind the ring; RAD_LERP is slower so
   the lens opens and closes with a little mass. Recorded in the plan doc. */
const POS_LERP = 0.18;
const RAD_LERP = 0.12;
const EPS = 0.05;

/* Pointer handlers write tx/ty (and tr, on enter/leave). Nothing else.
   The rAF loop is the only code that touches the DOM. */
const s = { px: 0, py: 0, tx: 0, ty: 0, r: 0, tr: 0 };

/* Last-written values. -Infinity, NOT NaN: every comparison against NaN is
   false, so a NaN sentinel silently disables the dirty check forever and the
   loop spins without ever writing. -Infinity makes the first frame dirty. */
let wx = -Infinity, wy = -Infinity, wr = -Infinity, wtx = -Infinity, wty = -Infinity;
let ringOn = false;
let raf = 0;
let heroLeft = 0, heroTop = 0, restR = 0;
let detach: (() => void) | null = null;

/* Half-pixel quantisation: sub-pixel movement on a mask edge shimmers. */
const q = (n: number) => Math.round(n * 2) / 2;

/* No scroll listener. The hero's document-space origin is cached; the live
   scroll offset is read per event, which is cheap and never goes stale. */
function cacheViewport() {
  const el = heroRef.value;
  if (!el) return;
  const rect = el.getBoundingClientRect();
  heroLeft = rect.left + window.scrollX;
  heroTop = rect.top + window.scrollY;
  restR = Math.min(Math.max(160, 0.18 * Math.min(window.innerWidth, window.innerHeight)), 280);
  if (s.tr > 0) s.tr = restR;
}

function frame() {
  s.px += (s.tx - s.px) * POS_LERP;
  s.py += (s.ty - s.py) * POS_LERP;
  s.r += (s.tr - s.r) * RAD_LERP;
  /* Snap the tail so the loop can actually reach a settled state. A 2px
     threshold is invisible (the feather's solid core at r=2 is 1.24px) and
     avoids ~10 extra frames of lerping an imperceptible circle. */
  if (Math.abs(s.tr - s.r) < 2) s.r = s.tr;
  /* When fully closed, snap position too — no point lerping an invisible
     center, and the writes keep the loop from going idle. */
  if (s.r === 0 && s.tr === 0) { s.px = s.tx; s.py = s.ty; }

  let dirty = false;

  if (Math.abs(s.px - wx) > EPS || Math.abs(s.py - wy) > EPS || Math.abs(s.r - wr) > EPS) {
    const c = circleRef.value;
    if (c) {
      c.setAttribute('cx', String(q(s.px)));
      c.setAttribute('cy', String(q(s.py)));
      c.setAttribute('r', String(q(s.r)));
    }
    wx = s.px; wy = s.py; wr = s.r;
    dirty = true;
  }

  if (Math.abs(s.tx - wtx) > EPS || Math.abs(s.ty - wty) > EPS) {
    const ring = ringRef.value;
    if (ring) ring.style.transform = 'translate3d(' + q(s.tx) + 'px,' + q(s.ty) + 'px,0)';
    wtx = s.tx; wty = s.ty;
    dirty = true;
  }

  const showRing = s.tr > 0;
  if (showRing !== ringOn) {
    if (ringRef.value) ringRef.value.style.opacity = showRing ? '1' : '0';
    ringOn = showRing;
    dirty = true;
  }

  /* Idle: nothing moved and the radius reached its target, so stop scheduling.
     A pointer event kicks it back. */
  raf = !dirty && s.r === s.tr ? 0 : requestAnimationFrame(frame);
}

function kick() {
  if (!raf) raf = requestAnimationFrame(frame);
}

function setTarget(e: PointerEvent) {
  s.tx = e.clientX + window.scrollX - heroLeft;
  s.ty = e.clientY + window.scrollY - heroTop;
}

/* Opening is driven by enter AND move, not enter alone: if the page loads with
   the cursor already inside a full-viewport hero, the pointer never crosses the
   boundary and `pointerenter` never fires — the lens would stay shut until the
   user left and came back. Idempotent, so a move costs nothing once open. */
function activate() {
  if (s.tr === restR) return;
  /* Open where the cursor already is rather than sliding in from the origin. */
  s.px = s.tx;
  s.py = s.ty;
  s.tr = restR;
}

function onEnter(e: PointerEvent) {
  setTarget(e);
  activate();
  kick();
}

function onMove(e: PointerEvent) {
  setTarget(e);
  activate();
  kick();
}

function onLeave() {
  s.tr = 0;
  kick();
}

onMounted(() => {
  const el = heroRef.value;
  if (!el) return;

  /* Coarse pointers and reduced-motion get a complete, lens-free professional
     layer. Loop 6 makes those first-class states with a real toggle; this is
     only the guard that stops them getting a broken half-lens meanwhile. */
  const fine = window.matchMedia('(hover: hover) and (pointer: fine)').matches;
  const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  if (!fine || reduced) return;

  cacheViewport();
  el.dataset.lensMode = 'lens';

  /* pointerrawupdate delivers moves at input rate rather than frame rate, so
     tx/ty are fresher; the rAF loop still gates every DOM write. */
  const moveEvent = 'onpointerrawupdate' in window ? 'pointerrawupdate' : 'pointermove';

  el.addEventListener('pointerenter', onEnter as EventListener);
  el.addEventListener('pointerleave', onLeave);
  el.addEventListener(moveEvent, onMove as EventListener, { passive: true });

  let t = 0;
  const onResize = () => {
    window.clearTimeout(t);
    t = window.setTimeout(cacheViewport, 150);
  };
  window.addEventListener('resize', onResize, { passive: true });

  detach = () => {
    window.clearTimeout(t);
    window.removeEventListener('resize', onResize);
    el.removeEventListener('pointerenter', onEnter as EventListener);
    el.removeEventListener('pointerleave', onLeave);
    el.removeEventListener(moveEvent, onMove as EventListener);
  };
});

onBeforeUnmount(() => {
  if (raf) cancelAnimationFrame(raf);
  raf = 0;
  detach?.();
});
</script>

<style scoped>
/* ============================================================
   THE REGISTRATION CONTRACT

   Every geometry value lives here, on .hero, and is consumed by both layers.
   Slot heights are explicit grid rows rather than content-driven, so the two
   stacks are identical by construction: a longer headline on one side can
   never push that side's lead, CTA or tags out of alignment with the other.
   ============================================================ */
.hero {
  /* — type scale. 44 → 96px display; leading lands on 112px (4 × 28px baseline)
       at the top of the ramp and holds a ~1.166 ratio all the way down. */
  --hero-fs: clamp(2.75rem, 7.2vw, 6rem);
  --hero-lh: clamp(3.2rem, 8.4vw, 7rem);
  --hero-track: -0.035em;
  --hero-title-lines: 2;

  --lead-fs: 1.0625rem;   /* 17px */
  --lead-lh: 1.75rem;     /* 28px — the shared baseline unit */
  --lead-lines: 4;
  --lead-measure: 46ch;

  --eyebrow-lh: 1.25rem;
  --cta-h: 3rem;
  /* The tag row is fixed too. Every grid row is now a pure function of these
     properties, so .hero__stack has one deterministic height and
     `align-content: center` cannot leak a content-length difference from the
     last row upward into every slot above it — which is exactly what it did
     at 2560px when this row was `auto`. */
  --tags-lines: 1;
  --tags-h: calc(var(--eyebrow-lh) * var(--tags-lines) + 0.5rem * (var(--tags-lines) - 1));

  /* — origin. Both layers anchor their stack to exactly these. */
  --hero-x: max(var(--sp-6), calc((100vw - var(--maxw-grid)) / 2));
  --hero-y: clamp(4.5rem, 11vh, 8rem);
  --hero-gap: 1.75rem;    /* 28px */

  /* — Clean Room (professional). docs/xray-plan.md §4 */
  --cr-ground: #f2f4f6;
  --cr-ink: #14161a;
  --cr-mute: #5a6068;
  --cr-signal: #0b63e5;
  --cr-hair: rgba(20, 22, 26, 0.1);

  /* — Safelight (artistic). One accent each, never two. */
  --sl-ground: #140a0c;
  --sl-print: #f0e4d9;
  --sl-mute: #b39c90;
  --sl-safelight: #e4465a;

  /* Shared display face. BOTH layers use it — that is what lets the two
     headlines hold the same box, and what makes a font swap harmless. */
  --hero-display: 'Inter Tight', 'Inter', system-ui, sans-serif;

  position: relative;
  min-height: 100svh;
  overflow: hidden;
  isolation: isolate;
}

.hero__layer {
  position: absolute;
  inset: 0;
  display: grid;
  align-content: center;
}

.hero__layer--pro {
  z-index: 0;
  background: var(--cr-ground);
  color: var(--cr-ink);
}

/* No lens (coarse pointer, reduced motion, no JS) means the artistic layer is
   simply not there and the professional layer is complete on its own. */
.hero__layer--art {
  z-index: 1;
  background: var(--sl-ground);
  color: var(--sl-print);
  opacity: 0;
}

.hero[data-lens-mode='lens'] .hero__layer--art {
  opacity: 1;
  -webkit-mask-image: url(#xray-lens);
  mask: url(#xray-lens);
}

/* The native cursor is hidden only inside the hero, and only while the lens is
   actually running — never `html *`, which is what the deleted global cursor
   did. Anything clickable keeps a pointer so you can still see what is. */
.hero[data-lens-mode='lens'] { cursor: none; }
.hero[data-lens-mode='lens'] :is(a, button, [role='button']) { cursor: pointer; }

.hero__defs { position: absolute; width: 0; height: 0; overflow: hidden; }

.hero__lens-ui {
  position: absolute;
  inset: 0;
  z-index: 2;
  pointer-events: none;
}

/* Negative margin centres the ring on the point, so the rAF loop writes raw
   coordinates and the transform stays a pure translate. */
.hero__ring {
  --ring: 34px;
  position: absolute;
  top: 0;
  left: 0;
  width: var(--ring);
  height: var(--ring);
  margin: calc(var(--ring) / -2);
  border: 1.5px solid #fff;
  border-radius: 50%;
  mix-blend-mode: difference;
  pointer-events: none;
  opacity: 0;
  transition: opacity 220ms var(--ease-out);
  will-change: transform;
}

/* ── The stack. Identical in both layers, by construction. ────────── */
/* --hero-x is the GUTTER, and the column is sized by subtracting it rather
   than by padding a max-width box: with border-box, `max-width: 1360px` plus
   `padding-inline: 600px` leaves a 160px column at 2560px, which is what broke
   registration the first time this ran. */
.hero__stack {
  width: min(calc(100% - 2 * var(--hero-x)), var(--maxw-grid));
  margin-inline: auto;
  padding-block: var(--hero-y) var(--hero-gap);

  display: grid;
  grid-template-rows:
    var(--eyebrow-lh)
    calc(var(--hero-lh) * var(--hero-title-lines))
    calc(var(--lead-lh) * var(--lead-lines))
    var(--cta-h)
    var(--tags-h);
  gap: var(--hero-gap);
  justify-items: start;
}

.hero__eyebrow {
  font-family: var(--font-mono);
  font-size: 0.75rem;
  line-height: var(--eyebrow-lh);
  letter-spacing: 0.14em;
  text-transform: uppercase;
  margin: 0;
}

.hero__title {
  font-family: var(--hero-display);
  font-size: var(--hero-fs);
  line-height: var(--hero-lh);
  letter-spacing: var(--hero-track);
  font-weight: 600;
  margin: 0;
  max-width: 15ch;
  text-wrap: balance;
}

.hero__lead {
  font-family: var(--font-body);
  font-size: var(--lead-fs);
  line-height: var(--lead-lh);
  margin: 0;
  max-width: var(--lead-measure);
}

.hero__actions {
  display: flex;
  align-items: center;
  height: var(--cta-h);
}

.hero__cta {
  display: inline-flex;
  align-items: center;
  height: var(--cta-h);
  padding-inline: 1.75rem;
  border-radius: 999px;
  font-family: var(--font-body);
  font-size: 1.0625rem;
  font-weight: 600;
  text-decoration: none;
  white-space: nowrap;
}

.hero__tags {
  list-style: none;
  margin: 0;
  padding: 0;
  display: flex;
  flex-wrap: wrap;
  gap: 0.5rem 1.75rem;
  font-family: var(--font-mono);
  font-size: 0.75rem;
  line-height: var(--eyebrow-lh);
}

.hero__tags li {
  display: flex;
  gap: 0.5rem;
}

.hero__tag-label { text-transform: uppercase; letter-spacing: 0.1em; }

.hero__chapter-link { text-decoration: none; border-bottom: 1px solid currentColor; }

/* ── Per-layer colour. Colour only — never geometry. ──────────────── */
.hero__layer--pro .hero__eyebrow,
.hero__layer--pro .hero__tag-label { color: var(--cr-signal); }
.hero__layer--pro .hero__lead,
.hero__layer--pro .hero__tag-detail { color: var(--cr-mute); }
.hero__layer--pro .hero__cta { background: var(--cr-signal); color: #fff; }
.hero__layer--pro .hero__chapter-link { color: var(--cr-ink); }
.hero__layer--pro .hero__cta:focus-visible,
.hero__layer--pro .hero__chapter-link:focus-visible {
  outline: 2px solid var(--cr-signal);
  outline-offset: 3px;
}

.hero__layer--art .hero__eyebrow,
.hero__layer--art .hero__tag-label { color: var(--sl-safelight); }
.hero__layer--art .hero__lead,
.hero__layer--art .hero__tag-detail { color: var(--sl-mute); }
.hero__layer--art .hero__cta { background: var(--sl-safelight); color: var(--sl-ground); }
.hero__layer--art .hero__chapter-link { color: var(--sl-print); }

/* ── Widths. Only the shared custom properties change — never a rule that
     applies to one layer and not the other. ────────────────────────── */
@media (max-width: 900px) {
  .hero { --tags-lines: 2; }
}

@media (max-width: 600px) {
  .hero {
    --hero-title-lines: 3;
    --lead-lines: 5;
    --hero-gap: 1.25rem;
    --hero-x: var(--sp-5);
    --tags-lines: 3;
  }
}

@media (max-width: 400px) {
  .hero { --lead-lines: 6; --tags-lines: 4; }
}
</style>

// src/components/hero/XRayHero.tsx
import { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { heroPro, heroArt, heroTags, heroHint } from '../../content/xray';
import './XRayHero.css';

/* Loop 2: structure only. Loop 3: the lens. Loop 4: the ink spill. */

const layers = [
  { variant: 'pro' as const, copy: heroPro },
  { variant: 'art' as const, copy: heroArt },
];

/* Tuning. POS_LERP is the reveal's lag behind the ring; RAD_LERP is slower so
   the lens opens and closes with a little mass. Recorded in the plan doc. */
const POS_LERP = 0.18;
const RAD_LERP = 0.12;
const EPS = 0.05;

/* Ink spill (Loop 4). The blots are authored once at this local radius and
   never resized: only the group transform changes. See docs/loop4-plan.md for
   why that is load-bearing and not a style choice. */
const INK_R = 400;
/* Local units the baked texture spans, and the bitmap resolution behind it.
   These are independent: the <image> is 1024 user units wide however many
   pixels the PNG has. 768 measured no worse than 1024 and rasters faster. */
const INK_SPAN = 1024;
const INK_TEX = 768;
/* Fraction of the blot that is fully solid. Flood coverage is measured from the
   solid core, not the outer edge, and the bake reads the same constant: the
   gradient stop and the coverage maths can never drift apart. */
const INK_CORE = 0.8;
const INK_LAG = 0.25;   /* companion blot, ~4 frames = 66ms behind. */

/* Spring rather than a bezier because pointerup mid-expansion inherits velocity
   instead of restarting a timeline.
   The spec's 120/18 was measured and rejected: at that stiffness the blot is
   past the viewport edge in 80ms, so the irregular edge (the entire point of
   this loop) exists for one frame. These are the same damping ratio (zeta 0.82,
   ~1% overshoot: the paper sucking back) retuned to the spec's own 850ms
   expansion, which puts ~17 frames of visible edge on screen.
   Opening and closing are deliberately asymmetric: ink blooms slower than it
   is drawn back. Switching stiffness mid-flight is safe: the integrator carries
   position AND velocity across, so there is nothing to jump. */
const K_STIFF_OPEN = 33;    /* zeta*omega = 4.7, ~850ms */
const K_DAMP_OPEN = 9.4;
const K_STIFF_SHUT = 66;    /* zeta*omega = 6.7, ~600ms */
const K_DAMP_SHUT = 13.3;
const SUBSTEP = 0.008;  /* fixed integration step; a dropped frame cannot blow up. */

/* Half-pixel quantisation: sub-pixel movement on a mask edge shimmers. */
const q = (n: number) => Math.round(n * 2) / 2;

/* Run feTurbulence + feDisplacementMap exactly once, off the critical path, and
   keep only the bitmap. Deterministic (seed 7), so every visitor gets the same
   blot and the shape can be reasoned about. */
async function bakeInk(): Promise<string> {
  const half = INK_SPAN / 2;
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="${INK_TEX}" height="${INK_TEX}" ` +
    `viewBox="-${half} -${half} ${INK_SPAN} ${INK_SPAN}"><defs>` +
    /* Tighter than the lens's own feather on purpose. The lens is an optic and
       wants a wide fade; ink on paper has a wet edge with a small fringe, and
       at flood scale the lens's wide stop smeared a third of the viewport into
       a grey band that buried the displacement detail it exists to show. */
    `<radialGradient id="f">` +
    `<stop offset="0" stop-color="#fff" stop-opacity="1"/>` +
    `<stop offset="${INK_CORE}" stop-color="#fff" stop-opacity="1"/>` +
    `<stop offset="0.92" stop-color="#fff" stop-opacity="0.4"/>` +
    `<stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient>` +
    `<filter id="k" x="-30%" y="-30%" width="160%" height="160%" color-interpolation-filters="sRGB">` +
    `<feTurbulence type="fractalNoise" baseFrequency="0.012 0.018" numOctaves="3" seed="7" result="n"/>` +
    `<feDisplacementMap in="SourceGraphic" in2="n" scale="40" xChannelSelector="R" yChannelSelector="G"/>` +
    `</filter></defs>` +
    `<circle cx="0" cy="0" r="${INK_R}" fill="url(#f)" filter="url(#k)"/></svg>`;

  const img = new Image();
  img.src = 'data:image/svg+xml;charset=utf-8,' + encodeURIComponent(svg);
  await img.decode();
  const cv = document.createElement('canvas');
  cv.width = cv.height = INK_TEX;
  cv.getContext('2d')!.drawImage(img, 0, 0, INK_TEX, INK_TEX);
  return cv.toDataURL('image/png');
}

export default function XRayHero() {
  const heroRef = useRef<HTMLElement>(null);
  const circleRef = useRef<SVGCircleElement>(null);
  const ringRef = useRef<HTMLDivElement>(null);
  const inkRef = useRef<SVGGElement>(null);
  const inkARef = useRef<SVGGElement>(null);
  const inkBRef = useRef<SVGGElement>(null);
  const inkImgARef = useRef<SVGImageElement>(null);
  const inkImgBRef = useRef<SVGImageElement>(null);
  /* Fallback circles are removed from the tree the moment the texture lands. */
  const [baked, setBaked] = useState(false);

  useEffect(() => {
    const el = heroRef.current;
    if (!el) return;

    /* Coarse pointers and reduced-motion get a complete, lens-free professional
       layer. Loop 6 makes those first-class states with a real toggle; this is
       only the guard that stops them getting a broken half-lens meanwhile. */
    const fine = window.matchMedia('(hover: hover) and (pointer: fine)').matches;
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    if (!fine || reduced) return;

    /* Pointer handlers write tx/ty (and tr/tk, on enter/leave/down/up). Nothing
       else. The rAF loop is the only code that touches the DOM. */
    const s = { px: 0, py: 0, tx: 0, ty: 0, r: 0, tr: 0, k: 0, tk: 0, kb: 0 };
    let kv = 0;      /* blot scale velocity: the spring's other half. */
    let last = 0;    /* previous frame timestamp; 0 means "loop just restarted". */

    /* Last-written values. -Infinity, NOT NaN: every comparison against NaN is
       false, so a NaN sentinel silently disables the dirty check forever and the
       loop spins without ever writing. -Infinity makes the first frame dirty. */
    let wx = -Infinity, wy = -Infinity, wr = -Infinity, wtx = -Infinity, wty = -Infinity;
    let wk = -Infinity, wkb = -Infinity;
    let ringOn = false;
    let inkOn = false;
    let floodOn = false;
    let raf = 0;
    let heroLeft = 0, heroTop = 0, restR = 0;
    let kFlood = 0, floodAt = 0;
    let alive = true;

    /* Idle-time, and failure is survivable: without the texture the blots stay
       plain feathered circles, which spill correctly and merely lack the edge. */
    const run = () => {
      bakeInk().then((href) => {
        if (!alive) return;
        inkImgARef.current?.setAttribute('href', href);
        inkImgBRef.current?.setAttribute('href', href);
        setBaked(true);
      }).catch(() => { /* keep the circles */ });
    };
    const hasIdle = 'requestIdleCallback' in window;
    const idle = hasIdle ? window.requestIdleCallback(run, { timeout: 2000 }) : window.setTimeout(run, 300);

    /* No scroll listener. The hero's document-space origin is cached; the live
       scroll offset is read per event, which is cheap and never goes stale. */
    const cacheViewport = () => {
      const rect = el.getBoundingClientRect();
      heroLeft = rect.left + window.scrollX;
      heroTop = rect.top + window.scrollY;
      restR = Math.min(Math.max(160, 0.18 * Math.min(window.innerWidth, window.innerHeight)), 280);
      if (s.tr > 0) s.tr = restR;

      /* Flood must cover every corner from any pointer position, so the SOLID
         core, not the outer feather, has to reach 1.15 x the viewport diagonal. */
      const diag = Math.hypot(window.innerWidth, window.innerHeight);
      kFlood = (diag * 1.15) / (INK_R * INK_CORE);
      floodAt = (diag * 0.6) / (INK_R * INK_CORE);
      if (s.tk > 0) s.tk = kFlood;
    };

    const frame = (now: number) => {
      /* Clamped: a backgrounded tab returns with a multi-second gap, and a
         spring handed a 30s step integrates to infinity. Clamping is also what
         stops the catch-up jump on tab return (Loop 8 item 3). */
      const dt = last ? Math.min((now - last) / 1000, 0.1) : 1 / 60;
      last = now;

      s.px += (s.tx - s.px) * POS_LERP;
      s.py += (s.ty - s.py) * POS_LERP;
      s.r += (s.tr - s.r) * RAD_LERP;

      /* Blot scale. Fixed-timestep so the shape of the motion does not change
         with the frame rate. Intent, not the instantaneous comparison: `tk > k`
         flips during the opening overshoot and would hand the shut spring the
         one moment the overshoot is supposed to happen. */
      const opening = s.tk > 0;
      const stiff = opening ? K_STIFF_OPEN : K_STIFF_SHUT;
      const damp = opening ? K_DAMP_OPEN : K_DAMP_SHUT;
      for (let acc = dt; acc > 0; acc -= SUBSTEP) {
        const h = Math.min(acc, SUBSTEP);
        kv += (-stiff * (s.k - s.tk) - damp * kv) * h;
        s.k += kv * h;
      }
      if (s.k < 0) { s.k = 0; kv = 0; }
      /* Settle: close enough AND slow enough. Velocity has to be in the test or
         a blot passing through its target at speed reads as "arrived". */
      if (Math.abs(s.tk - s.k) < 0.01 && Math.abs(kv) < 0.05) { s.k = s.tk; kv = 0; }
      s.kb += (s.k - s.kb) * INK_LAG;
      if (Math.abs(s.k - s.kb) < 0.01) s.kb = s.k;
      /* Snap the tail so the loop can actually reach a settled state. A 2px
         threshold is invisible (the feather's solid core at r=2 is ~1.5px) and
         avoids ~10 extra frames of lerping an imperceptible circle. */
      if (Math.abs(s.tr - s.r) < 2) s.r = s.tr;
      /* When fully closed, snap position too: no point lerping an invisible
         center, and the writes keep the loop from going idle. The ink has to be
         gone as well, or a blot still receding would jump to the pointer. */
      if (s.r === 0 && s.tr === 0 && s.k === 0 && s.tk === 0) { s.px = s.tx; s.py = s.ty; }

      let dirty = false;
      /* Captured BEFORE the circle write, which overwrites wx/wy. The blots hang
         off the same lerped centre, so they need the same answer. */
      const movedPos = Math.abs(s.px - wx) > EPS || Math.abs(s.py - wy) > EPS;

      if (movedPos || Math.abs(s.r - wr) > EPS) {
        const c = circleRef.current;
        if (c) {
          c.setAttribute('cx', String(q(s.px)));
          c.setAttribute('cy', String(q(s.py)));
          c.setAttribute('r', String(q(s.r)));
        }
        wx = s.px; wy = s.py; wr = s.r;
        dirty = true;
      }

      if (Math.abs(s.tx - wtx) > EPS || Math.abs(s.ty - wty) > EPS) {
        const ring = ringRef.current;
        if (ring) ring.style.transform = 'translate3d(' + q(s.tx) + 'px,' + q(s.ty) + 'px,0)';
        wtx = s.tx; wty = s.ty;
        dirty = true;
      }

      /* The ink group is display:none until it has something to draw, so the
         turbulence filter costs exactly zero before the first pointerdown. This
         is a discrete state change, not a per-frame write. */
      const showInk = s.k > 0 || s.tk > 0;
      if (showInk !== inkOn) {
        if (inkRef.current) inkRef.current.style.display = showInk ? 'block' : 'none';
        inkOn = showInk;
        dirty = true;
      }

      if (showInk && (movedPos || Math.abs(s.k - wk) > 0.002)) {
        inkARef.current?.setAttribute('transform', `translate(${q(s.px)} ${q(s.py)}) scale(${s.k.toFixed(4)})`);
        wk = s.k;
        dirty = true;
      }

      if (showInk && (movedPos || Math.abs(s.kb - wkb) > 0.002)) {
        inkBRef.current?.setAttribute('transform', `translate(${q(s.px)} ${q(s.py)}) scale(${(s.kb * 0.85).toFixed(4)})`);
        wkb = s.kb;
        dirty = true;
      }

      /* Past this point the lens has become the room: the ring has nothing left
         to point at, and the artistic layer's animations are allowed to run. */
      const flooded = s.k > floodAt;
      if (flooded !== floodOn) {
        el.toggleAttribute('data-flooded', flooded);
        floodOn = flooded;
        dirty = true;
      }

      const showRing = s.tr > 0 && !flooded;
      if (showRing !== ringOn) {
        if (ringRef.current) ringRef.current.style.opacity = showRing ? '1' : '0';
        ringOn = showRing;
        dirty = true;
      }

      /* Idle: nothing moved and both the radius and the blot reached their
         targets, so stop scheduling. A pointer event kicks it back. */
      const settled = !dirty && s.r === s.tr && s.k === s.tk;
      if (settled) { raf = 0; last = 0; } else raf = requestAnimationFrame(frame);
    };

    const kick = () => {
      if (!raf) { last = 0; raf = requestAnimationFrame(frame); }
    };

    const setTarget = (e: PointerEvent) => {
      s.tx = e.clientX + window.scrollX - heroLeft;
      s.ty = e.clientY + window.scrollY - heroTop;
    };

    /* Opening is driven by enter AND move, not enter alone: if the page loads
       with the cursor already inside a full-viewport hero, the pointer never
       crosses the boundary and `pointerenter` never fires: the lens would stay
       shut until the user left and came back. Idempotent, so a move costs
       nothing once open. */
    const activate = () => {
      if (s.tr === restR) return;
      /* Open where the cursor already is rather than sliding in from the origin. */
      s.px = s.tx;
      s.py = s.ty;
      s.tr = restR;
    };

    const onEnter = (e: Event) => { setTarget(e as PointerEvent); activate(); kick(); };
    const onMove = (e: Event) => { setTarget(e as PointerEvent); activate(); kick(); };
    const onLeave = () => { s.tr = 0; s.tk = 0; kick(); };

    /* Hold to flood. Pointer capture is not a nicety: without it, dragging out
       of the window and releasing there never delivers a pointerup and the hero
       stays flooded forever. */
    const onDown = (ev: Event) => {
      const e = ev as PointerEvent;
      /* A click on the CTA should navigate, not stage a light show. */
      if ((e.target as Element | null)?.closest?.('a, button, [role="button"]')) return;
      setTarget(e);
      activate();
      s.tk = kFlood;
      try { el.setPointerCapture(e.pointerId); } catch { /* already gone */ }
      kick();
    };

    /* tk is a target, not a timeline, so click-click-click cannot queue: each
       event just moves where the spring is heading, from wherever it currently is. */
    const onUp = () => { s.tk = 0; kick(); };

    cacheViewport();
    el.dataset.lensMode = 'lens';

    /* pointerrawupdate delivers moves at input rate rather than frame rate, so
       tx/ty are fresher; the rAF loop still gates every DOM write. */
    const moveEvent = 'onpointerrawupdate' in window ? 'pointerrawupdate' : 'pointermove';

    el.addEventListener('pointerenter', onEnter);
    el.addEventListener('pointerleave', onLeave);
    el.addEventListener(moveEvent, onMove, { passive: true });
    el.addEventListener('pointerdown', onDown);
    el.addEventListener('pointerup', onUp);
    el.addEventListener('pointercancel', onUp);
    el.addEventListener('lostpointercapture', onUp);

    let t = 0;
    const onResize = () => {
      window.clearTimeout(t);
      t = window.setTimeout(cacheViewport, 150);
    };
    window.addEventListener('resize', onResize, { passive: true });

    return () => {
      alive = false;
      if (raf) cancelAnimationFrame(raf);
      raf = 0;
      if (hasIdle) window.cancelIdleCallback(idle);
      else window.clearTimeout(idle);
      window.clearTimeout(t);
      window.removeEventListener('resize', onResize);
      el.removeEventListener('pointerenter', onEnter);
      el.removeEventListener('pointerleave', onLeave);
      el.removeEventListener(moveEvent, onMove);
      el.removeEventListener('pointerdown', onDown);
      el.removeEventListener('pointerup', onUp);
      el.removeEventListener('pointercancel', onUp);
      el.removeEventListener('lostpointercapture', onUp);
      delete el.dataset.lensMode;
      el.removeAttribute('data-flooded');
    };
  }, []);

  return (
    <section ref={heroRef} className="hero" data-lens>
      {/* REGISTRATION IS THE WHOLE TRICK, so both layers come out of ONE template.
          A second hand-written layer would drift the first time someone edits one
          side and not the other. Every box below is sized from custom properties
          declared once on .hero: no layer may hardcode a geometry value. */}
      {layers.map((layer) => {
        const pro = layer.variant === 'pro';
        return (
          <div
            key={layer.variant}
            className={`hero__layer hero__layer--${layer.variant}`}
            aria-hidden={pro ? undefined : true}
            inert={pro ? undefined : true}
          >
            <div className="hero__stack">
              <p className="hero__eyebrow">{layer.copy.eyebrow}</p>

              {/* The artistic twin is a <p>, not an <h1>: two h1s in one section is
                  a document-outline bug even when one of them is aria-hidden. */}
              {pro
                ? <h1 className="hero__title">{layer.copy.title}</h1>
                : <p className="hero__title">{layer.copy.title}</p>}

              <p className="hero__lead">{layer.copy.lead}</p>

              <div className="hero__actions">
                {pro
                  ? <Link className="hero__cta" to="/work#projects">{layer.copy.action}</Link>
                  /* Decorative twin. Holds the slot open so the layers stay
                     registered; inert, so it can never take focus. */
                  : <span className="hero__cta hero__cta--ghost">{layer.copy.action}</span>}
              </div>

              <ul className="hero__tags">
                {heroTags.map((tag) => (
                  <li key={tag.label}>
                    <span className="hero__tag-label">{tag.label}</span>
                    <span className="hero__tag-detail">{tag.detail}</span>
                  </li>
                ))}
                <li>
                  {pro
                    ? <Link className="hero__chapter-link" to="/creator">Chapter Two — the other half</Link>
                    : <span className="hero__chapter-link">Chapter Two — the other half</span>}
                </li>
              </ul>
            </div>

            {/* Out of grid flow, identical coordinates in both layers: it registers
                under the lens without touching a stack row. Decorative, so it is
                hidden from assistive tech; the pro layer is complete without it. */}
            <p className="hero__hint" aria-hidden="true">
              <span className="hero__hint-ring"></span>{heroHint}
            </p>
          </div>
        );
      })}

      <div className="hero__lens-ui" aria-hidden="true">
        {/* The ring sits at the TRUE pointer position while the reveal below it
            lerps behind. That lag is the whole feel: a lens being dragged, not a
            CSS variable being assigned. */}
        <div ref={ringRef} className="hero__ring"></div>
      </div>

      {/* Path B from docs/xray-plan.md section 9. The circle's radial fill IS
          the 3-stop feather; only cx/cy/r change per frame. */}
      <svg className="hero__defs" aria-hidden="true" focusable="false">
        <defs>
          <radialGradient id="xray-feather">
            <stop offset="0" stopColor="#fff" stopOpacity="1" />
            <stop offset="0.74" stopColor="#fff" stopOpacity="1" />
            <stop offset="0.9" stopColor="#fff" stopOpacity="0.4" />
            <stop offset="1" stopColor="#fff" stopOpacity="0" />
          </radialGradient>

          {/* maskUnits is deliberately ABSENT (i.e. objectBoundingBox). It is the
              region (x/y/width/height, defaulting to -10%/120%), not the
              contents. Under userSpaceOnUse those percentages resolve against
              THIS svg's viewport, which is 0x0, so the mask region collapses to
              nothing and the layer is masked out entirely. maskContentUnits
              still defaults to userSpaceOnUse, which is what keeps cx/cy/r in
              plain pixels. Do not "tidy" this attribute back in. */}
          <mask id="xray-lens">
            <circle ref={circleRef} cx="-9999" cy="-9999" r="0" fill="url(#xray-feather)" />

            {/* INK SPILL (Loop 4). The displaced edge is BAKED to a bitmap once
                (see bakeInk) and then only ever moved by the group transform.
                A live feDisplacementMap here measured 26.6fps with 105ms long
                tasks: Chromium re-rasterises an SVG filter at whatever device
                scale the ancestor transform implies, so "constant local
                geometry" buys nothing. The circles are the pre-bake fallback and
                are removed the moment the texture lands.
                The offset and the 0.85 scale are what make two blots read as
                liquid rather than as one circle. */}
            <g ref={inkRef} className="hero__ink">
              <g ref={inkBRef} className="hero__ink-b" opacity="0.55">
                {!baked && <circle className="hero__ink-fallback" cx="-150" cy="95" r={INK_R} fill="url(#xray-feather)" />}
                <image
                  ref={inkImgBRef}
                  x={-INK_SPAN / 2 - 150} y={-INK_SPAN / 2 + 95}
                  width={INK_SPAN} height={INK_SPAN}
                />
              </g>
              <g ref={inkARef}>
                {!baked && <circle className="hero__ink-fallback" cx="0" cy="0" r={INK_R} fill="url(#xray-feather)" />}
                <image
                  ref={inkImgARef}
                  x={-INK_SPAN / 2} y={-INK_SPAN / 2}
                  width={INK_SPAN} height={INK_SPAN}
                />
              </g>
            </g>
          </mask>
        </defs>
      </svg>
    </section>
  );
}
