// src/views/ProjectCasePage.vue
<template>
  <article v-if="project" class="case">
    <div class="container case__inner">
      <RouterLink to="/#projects" class="case__back">
        <span class="case__back-pip" aria-hidden="true">
          <svg viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round"><path d="M10 3.5 5.5 8l4.5 4.5" /></svg>
        </span>
        All projects
      </RouterLink>

      <header class="case__head">
        <p class="eyebrow-label eyebrow">{{ project.techLine }}</p>
        <h1 class="display-lg">{{ project.title }}</h1>
        <p class="case__oneliner">{{ project.oneLiner }}</p>

        <div class="case__links">
          <a v-if="project.live" :href="project.live" target="_blank" rel="noopener" class="btn btn--primary">Visit live site</a>
          <a v-if="project.github" :href="project.github" target="_blank" rel="noopener" class="btn btn--ghost">View on GitHub</a>
          <a
            v-for="l in project.extraLinks || []"
            :key="l.href"
            :href="l.href"
            target="_blank"
            rel="noopener"
            class="btn btn--ghost"
          >{{ l.label }}</a>
        </div>
      </header>

      <figure v-if="project.screenshot" class="case__shot">
        <img :src="project.screenshot" :alt="`${project.title} interface`" />
      </figure>

      <div class="case__body">
        <section class="case__block">
          <h2>Problem</h2>
          <p>{{ project.problem }}</p>
        </section>

        <section class="case__block">
          <h2>Approach</h2>
          <p>{{ project.approach }}</p>
        </section>

        <section v-if="project.stack?.length" class="case__block">
          <h2>Stack</h2>
          <ul class="case__stack">
            <li v-for="s in project.stack" :key="s.name">
              <strong>{{ s.name }}</strong>
              <span>{{ s.role }}</span>
            </li>
          </ul>
        </section>

        <section v-if="project.decisions?.length" class="case__block">
          <h2>Key decisions</h2>
          <ul class="case__decisions">
            <li v-for="(d, i) in project.decisions" :key="i">
              <span class="case__num mono-xs">{{ String(i + 1).padStart(2, '0') }}</span>
              <p>{{ d }}</p>
            </li>
          </ul>
        </section>

        <section v-if="project.outcome" class="case__block case__block--outcome">
          <h2>Outcome</h2>
          <p>{{ project.outcome }}</p>
        </section>
      </div>

      <nav class="case__pager">
        <RouterLink v-if="prev" :to="`/projects/${prev.slug}`" class="case__pager-link">
          <span class="mono-xs">Previous</span>
          <strong>{{ prev.title }}</strong>
        </RouterLink>
        <span v-else></span>
        <RouterLink v-if="next" :to="`/projects/${next.slug}`" class="case__pager-link case__pager-link--next">
          <span class="mono-xs">Next</span>
          <strong>{{ next.title }}</strong>
        </RouterLink>
      </nav>
    </div>
  </article>

  <!-- Unknown slug: say so instead of rendering a blank page. -->
  <div v-else class="container case__missing">
    <h1 class="display-md">Project not found</h1>
    <p>No case study matches “{{ slug }}”.</p>
    <RouterLink to="/#projects" class="btn btn--primary">Back to projects</RouterLink>
  </div>
</template>

<script setup lang="ts">
import { computed, watch } from 'vue';
import { RouterLink } from 'vue-router';
import { projectCases, getProjectCase } from '../content/projects';

const props = defineProps<{ slug?: string }>();

const project = computed(() => (props.slug ? getProjectCase(props.slug) : undefined));
const index = computed(() => projectCases.findIndex((p) => p.slug === props.slug));
const prev = computed(() => (index.value > 0 ? projectCases[index.value - 1] : null));
const next = computed(() =>
  index.value > -1 && index.value < projectCases.length - 1 ? projectCases[index.value + 1] : null,
);

// Router scrollBehavior handles route changes; this covers title only.
watch(
  project,
  (p) => {
    document.title = p ? `${p.title} — Kirtiraj Nitin Chaudhari` : 'Project not found';
  },
  { immediate: true },
);
</script>

<style scoped>
/* An editorial surface: ~980px measure, parchment ground, no chrome. */
.case {
  padding: calc(52px + var(--sp-8)) 0 var(--sp-9);
  background: var(--bg-parchment);
  min-height: 100svh;
}
.case__inner { max-width: var(--maxw-text); }

.case__back {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-size: 17px;
  letter-spacing: -0.022em;
  color: var(--accent);
  margin-bottom: var(--sp-7);
}
.case__back-pip {
  display: grid;
  place-items: center;
  transition: transform 340ms var(--ease-out);
}
.case__back-pip svg { width: 14px; height: 14px; }
.case__back:hover { text-decoration: underline; }
.case__back:hover .case__back-pip { transform: translateX(-3px); }

.eyebrow-label { margin-bottom: var(--sp-3); }

.case__head h1 { margin-bottom: var(--sp-4); }
.case__oneliner {
  font-family: var(--font-body);
  font-size: clamp(1.0625rem, 1.5vw, 1.5rem);
  font-weight: 300;
  line-height: 1.5;
  color: var(--text-muted);
  max-width: 60ch;
}
.case__links {
  display: flex;
  flex-wrap: wrap;
  gap: var(--sp-3);
  margin-top: var(--sp-6);
}

/* The screenshot is the product; it takes the one system drop-shadow. */
.case__shot {
  margin: var(--sp-8) 0;
  border-radius: var(--r-lg);
  overflow: hidden;
  background: var(--surface-solid);
  box-shadow: var(--product-shadow);
}
.case__shot img { width: 100%; display: block; }

.case__block {
  padding-top: var(--sp-6);
  margin-top: var(--sp-6);
  border-top: 1px solid var(--border);
}
.case__block h2 {
  font-family: var(--font-body);
  font-size: 14px;
  font-weight: 600;
  letter-spacing: -0.016em;
  color: var(--accent);
  margin-bottom: var(--sp-4);
}
.case__block p {
  color: var(--text-muted);
  font-size: 17px;
  line-height: 1.47;
  max-width: var(--maxw-prose);
}
.case__block--outcome p {
  color: var(--text);
  font-size: 1.3125rem;
  font-weight: 600;
  line-height: 1.19;
  letter-spacing: 0.011em;
}

.case__stack {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: var(--sp-4);
}
.case__stack li {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding-left: var(--sp-4);
  border-left: 1px solid var(--border-hair);
}
.case__stack strong {
  font-size: 17px;
  font-weight: 600;
  letter-spacing: -0.022em;
  color: var(--text);
}
.case__stack span {
  color: var(--text-muted);
  font-size: 14px;
  line-height: 1.43;
  letter-spacing: -0.016em;
}

.case__decisions { display: flex; flex-direction: column; gap: var(--sp-4); }
.case__decisions li { display: flex; gap: var(--sp-4); align-items: flex-start; }
.case__num {
  color: var(--accent);
  font-size: 14px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
  padding-top: 3px;
  flex-shrink: 0;
}

.case__pager {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: var(--sp-4);
  margin-top: var(--sp-9);
  padding-top: var(--sp-6);
  border-top: 1px solid var(--border);
}
.case__pager-link {
  display: flex;
  flex-direction: column;
  gap: 6px;
  padding: var(--sp-5);
  border: 1px solid var(--border);
  border-radius: var(--r-lg);
  background: var(--surface-solid);
  transition: border-color 250ms;
}
.case__pager-link:hover { border-color: var(--accent); }
.case__pager-link:active { transform: scale(0.99); }
.case__pager-link span {
  color: var(--text-faint);
  font-size: 12px;
  letter-spacing: -0.01em;
}
.case__pager-link strong {
  font-size: 17px;
  font-weight: 600;
  letter-spacing: -0.022em;
  color: var(--accent);
}
.case__pager-link--next { text-align: right; }

.case__missing {
  min-height: 100svh;
  display: flex;
  flex-direction: column;
  align-items: flex-start;
  justify-content: center;
  gap: var(--sp-4);
}
.case__missing p { color: var(--text-muted); }

@media (max-width: 640px) {
  .case__pager { grid-template-columns: 1fr; }
  .case__pager-link--next { text-align: left; }
}
</style>

// src/views/ProjectCasePage.tsx
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowUpRight } from 'lucide-react';
import { projectCases, getProjectCase } from '../content/projects';
import PageShell from '../components/shell/PageShell';
import Section from '../components/shell/Section';
import Reveal from '../components/shell/Reveal';

const pill =
  'inline-flex items-center gap-1.5 rounded-full px-5 py-2.5 text-sm font-semibold transition-colors duration-300 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-white';

export default function ProjectCasePage() {
  const { slug } = useParams();
  const project = slug ? getProjectCase(slug) : undefined;
  const index = projectCases.findIndex((p) => p.slug === slug);
  const prev = index > 0 ? projectCases[index - 1] : null;
  const next = index > -1 && index < projectCases.length - 1 ? projectCases[index + 1] : null;

  /* Unknown slug: say so instead of rendering a blank page. */
  if (!project) {
    return (
      <PageShell title="Project not found">
        <h1 className="text-4xl font-semibold tracking-tight sm:text-6xl">That project doesn't exist.</h1>
        <p className="mt-6 text-[#f7ece7]/75">Nothing matches &ldquo;{slug}&rdquo;.</p>
        <Link to="/work" className={`${pill} mt-8 bg-white text-neutral-900`}>Back to work</Link>
      </PageShell>
    );
  }

  return (
    <PageShell title={project.title}>
      <Link to="/work#projects" className="inline-flex items-center gap-2 text-sm text-[#f7ece7]/70 hover:text-white">
        <ArrowLeft size={16} strokeWidth={1.75} />
        All projects
      </Link>

      <header className="mt-8 pb-12">
        <p className="font-mono text-xs uppercase tracking-[0.14em] text-[#ff7a66]">{project.techLine}</p>
        <h1 className="mt-4 text-balance text-5xl font-semibold leading-[1.02] tracking-[-0.035em] sm:text-7xl">{project.title}</h1>
        <p className="mt-6 max-w-[52ch] text-lg leading-relaxed text-[#f7ece7]/80">{project.oneLiner}</p>

        <div className="mt-8 flex flex-wrap gap-3">
          {project.live && (
            <a href={project.live} target="_blank" rel="noopener" className={`${pill} bg-white text-neutral-900 hover:bg-white/90`}>
              Visit the site <ArrowUpRight size={15} strokeWidth={1.75} />
            </a>
          )}
          {project.github && (
            <a href={project.github} target="_blank" rel="noopener" className={`${pill} border border-white/30 text-white hover:bg-white/10`}>
              Code on GitHub
            </a>
          )}
          {(project.extraLinks || []).map((l) => (
            <a key={l.href} href={l.href} target="_blank" rel="noopener" className={`${pill} border border-white/30 text-white hover:bg-white/10`}>
              {l.label}
            </a>
          ))}
        </div>
      </header>

      {project.screenshot && (
        <Reveal>
          <figure className="rounded-[2rem] border border-white/15 bg-white/[0.06] p-2">
            <img src={project.screenshot} alt={`${project.title} interface`} className="w-full rounded-[1.5rem]" />
          </figure>
        </Reveal>
      )}

      <Section title="The problem">
        <p className="max-w-[62ch] text-lg leading-relaxed text-[#f7ece7]/85">{project.problem}</p>
      </Section>

      <Section title="The approach">
        <p className="max-w-[62ch] text-lg leading-relaxed text-[#f7ece7]/85">{project.approach}</p>
      </Section>

      {project.stack?.length ? (
        <Section title="Stack">
          <dl className="divide-y divide-white/10 border-y border-white/10">
            {project.stack.map((s) => (
              <div key={s.name} className="grid gap-1 py-4 sm:grid-cols-[12rem_minmax(0,1fr)] sm:gap-6">
                <dt className="font-medium text-white">{s.name}</dt>
                <dd className="text-[#f7ece7]/70">{s.role}</dd>
              </div>
            ))}
          </dl>
        </Section>
      ) : null}

      {project.decisions?.length ? (
        <Section title="Decisions along the way">
          <ol className="space-y-6">
            {project.decisions.map((d, i) => (
              <li key={i} className="grid grid-cols-[2.25rem_minmax(0,1fr)] gap-x-4">
                <span className="pt-0.5 font-mono text-sm text-[#ff7a66]">{String(i + 1).padStart(2, '0')}</span>
                <p className="max-w-[62ch] leading-relaxed text-[#f7ece7]/80">{d}</p>
              </li>
            ))}
          </ol>
        </Section>
      ) : null}

      {project.outcome && (
        <Section title="What came out of it">
          <p className="max-w-[62ch] text-xl leading-snug text-white">{project.outcome}</p>
        </Section>
      )}

      <nav aria-label="More projects" className="grid gap-4 border-t border-white/10 pt-10 sm:grid-cols-2">
        {prev ? (
          <Link to={`/projects/${prev.slug}`} className="rounded-2xl border border-white/12 p-5 transition-colors hover:bg-white/5">
            <span className="text-sm text-[#f7ece7]/55">Previous</span>
            <span className="mt-1 block text-lg font-semibold text-white">{prev.title}</span>
          </Link>
        ) : <span />}
        {next && (
          <Link to={`/projects/${next.slug}`} className="rounded-2xl border border-white/12 p-5 text-left transition-colors hover:bg-white/5 sm:text-right">
            <span className="text-sm text-[#f7ece7]/55">Next</span>
            <span className="mt-1 block text-lg font-semibold text-white">{next.title}</span>
          </Link>
        )}
      </nav>
    </PageShell>
  );
}
