// components/novel/chapter-two/MusicSection.tsx
"use client";

/*
 * Music — the most complete section, restyled onto the board.
 *
 * Debut single as a pinned handbill (the centrepiece), the two platform
 * profiles as smaller stapled cards under it, and the tabla reels as a
 * contact sheet. The reels keep the drag-scroll interaction they already
 * had; only the frame around them changed. Every embed here is the real
 * one — nothing is a mock.
 */

import Image from "next/image";
import { Reveal } from "../Reveal";
import { LazyInstagram } from "./LazyInstagram";
import { SectionHeader } from "./SectionHeader";
import { Pin, Pinned, PinnedGroup, Staple, Tape, crayon } from "./Pinboard";
import { musicSection } from "@/content/novel";

const SPOTIFY_GREEN = "#1DB954";
const YOUTUBE_RED = "#FF0000";

/* ——— Stapled platform card ——————————————————————————————————— */
function StapledCard({
  image,
  imageAlt,
  name,
  meta,
  bio,
  ctaLabel,
  ctaHref,
  brandDot,
  caption,
  tilt,
}: {
  image: string;
  imageAlt: string;
  name: string;
  meta: string;
  bio: string;
  ctaLabel: string;
  ctaHref: string;
  brandDot: React.ReactNode;
  caption: string;
  tilt: number;
}) {
  return (
    <Pinned tilt={tilt} className="border border-border bg-surface p-2">
      <Staple className="-top-1 left-1/2 -translate-x-1/2" rotate={tilt > 0 ? -5 : 5} />
      <div className="flex items-center gap-4 p-4">
        <Image
          src={image}
          alt={imageAlt}
          width={96}
          height={96}
          className="h-16 w-16 shrink-0 rounded-sm border border-border object-cover md:h-20 md:w-20"
        />
        <div className="min-w-0 flex-1">
          <span className="block truncate text-base font-semibold text-text">
            {name}
          </span>
          <span
            className="mt-1 inline-block rounded-full px-2.5 py-0.5 text-[11px] tracking-wide text-text"
            style={{ backgroundColor: crayon("sun") }}
          >
            {meta}
          </span>
          <p className="mt-2 text-sm leading-snug text-text-muted">{bio}</p>
          <a
            href={ctaHref}
            target="_blank"
            rel="noopener noreferrer"
            className="mt-3 inline-flex items-center gap-2 rounded-full border border-border px-4 py-1.5 text-sm tracking-wide text-text transition-colors duration-[var(--dur-ui)] hover:border-text"
          >
            {brandDot}
            {ctaLabel}
          </a>
        </div>
      </div>
      <span className="type-hand block px-3 pb-1 text-lg text-text-muted">
        {caption}
      </span>
    </Pinned>
  );
}

export function MusicSection() {
  return (
    /* The handbill's rotated corner tapes overhang by a few px on a phone;
       clip that axis only, leaving vertical overhang (tape tops) visible. */
    <section aria-label="Music" className="overflow-x-clip py-16 md:py-24">
      <SectionHeader
        note="keeping taal…"
        title={musicSection.heading}
        highlight="Musician"
        hue="peach"
      />

      <div className="mx-auto max-w-6xl px-6">
        <Reveal className="mt-12 md:mt-16">
          <p className="max-w-xl text-base leading-relaxed text-text-muted md:text-lg">
            {musicSection.body}
          </p>
        </Reveal>

        <PinnedGroup className="mt-16 md:mt-20">
          {/* ── 1 · The handbill — debut single, centre stage ── */}
          <div className="flex justify-center">
            <div className="w-full max-w-lg">
              <Pinned
                tilt={-2}
                className="border border-border bg-surface px-5 pb-5 pt-8 md:px-7 md:pb-7"
              >
                <Pin hue="peach" className="-top-2 left-1/2 -translate-x-1/2" />
                <Tape hue="pink" className="-top-3 -left-4" rotate={-38} />
                <Tape hue="sun" className="-top-3 -right-4" rotate={38} />

                <span className="type-hand block text-center text-2xl text-text-muted">
                  and then, a first…
                </span>

                <div className="mt-5 flex justify-center">
                  <Image
                    src={musicSection.artistImage}
                    alt={`${musicSection.debutTitle} — single artwork`}
                    width={300}
                    height={300}
                    className="w-40 border border-border object-cover shadow-[var(--pin-shadow-flat)] md:w-48"
                  />
                </div>

                <span className="type-heading mt-5 block text-center text-xs tracking-[0.35em] text-text-muted">
                  {musicSection.debutLabel.toUpperCase()}
                </span>
                <h4
                  className="type-heading mt-2 text-center text-[clamp(1.75rem,5vw,2.75rem)] leading-[0.95] text-text"
                  style={{ textWrap: "balance" }}
                >
                  {musicSection.debutTitle}
                </h4>

                {/* Rule, drawn rather than ruled. */}
                <svg
                  aria-hidden
                  viewBox="0 0 240 8"
                  className="mx-auto mt-4 h-2 w-40"
                  fill="none"
                >
                  <path
                    d="M2 5C42 2 82 2 122 4C162 6 202 6 238 3"
                    stroke={crayon("peach")}
                    strokeWidth="2.5"
                    strokeLinecap="round"
                  />
                </svg>

                <p className="type-serif mx-auto mt-5 max-w-md text-center text-base italic leading-relaxed text-text-muted">
                  {musicSection.debutStory}
                </p>

                <iframe
                  src={musicSection.spotifyEmbedUrl}
                  width="100%"
                  height="152"
                  frameBorder="0"
                  allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
                  loading="lazy"
                  title={`${musicSection.debutTitle} — debut single on Spotify`}
                  className="mt-6 rounded"
                />

                <div className="mt-1 flex justify-center">
                  <a
                    href={musicSection.spotifyTrackUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="type-hand text-lg text-text-muted underline-offset-4 transition-colors duration-[var(--dur-ui)] hover:text-text hover:underline"
                  >
                    open the track ↗
                  </a>
                </div>
              </Pinned>
            </div>
          </div>

          {/* ── 2 · Stapled platform cards, smaller, beneath ── */}
          <div className="mx-auto mt-16 grid max-w-3xl grid-cols-1 gap-10 md:mt-20 md:grid-cols-2">
            <StapledCard
              tilt={-2.5}
              image={musicSection.youtubeImage}
              imageAlt="Musical Kirtiraj — YouTube channel profile picture"
              name={musicSection.youtubeName}
              meta={`${musicSection.youtubeHandle} · ${musicSection.youtubeStats}`}
              bio={musicSection.youtubeTagline}
              ctaLabel="Visit Channel"
              ctaHref={musicSection.youtubeChannelUrl}
              brandDot={
                <span
                  className="flex h-5 w-5 items-center justify-center rounded-full text-[9px] text-white"
                  style={{ backgroundColor: YOUTUBE_RED }}
                >
                  ▶
                </span>
              }
              caption="the YouTube channel"
            />
            <StapledCard
              tilt={3}
              image={musicSection.artistImage}
              imageAlt="Kirtiraj Nitin Chaudhari — Spotify artist artwork"
              name={musicSection.artistName}
              meta="Artist on Spotify"
              bio={musicSection.artistBio}
              ctaLabel="Listen on Spotify"
              ctaHref={musicSection.spotifyArtistUrl}
              brandDot={
                <span
                  className="h-2.5 w-2.5 rounded-full"
                  style={{ backgroundColor: SPOTIFY_GREEN }}
                />
              }
              caption="the artist page"
            />
          </div>
        </PinnedGroup>

        {/* ── 3 · Contact sheet — same drag-scroll, new frame ── */}
        <Reveal className="mt-20 md:mt-24">
          <div className="mb-5 flex items-baseline justify-between">
            <span className="type-hand text-2xl text-text-muted">
              taal, on camera…
            </span>
            <span className="text-sm text-text-muted">drag to browse →</span>
          </div>
        </Reveal>

        <Reveal>
          <div className="relative -mx-6 md:mx-0">
            <div className="filmstrip relative overflow-hidden px-6 py-6 md:px-8">
              {/* w-max + mx-auto rather than justify-center: on a scroll
                  container, centering an overflowing track pushes the first
                  frame past the left edge where it cannot be scrolled back. */}
              <div className="scrollbar-hide snap-x snap-mandatory overflow-x-auto py-3">
                <div className="mx-auto flex w-max items-start gap-5">
                  {musicSection.reels.map((reel) => (
                    <figure
                      key={reel.id}
                      className="w-[328px] shrink-0 snap-center bg-surface p-1.5"
                    >
                      <LazyInstagram
                        href={reel.href}
                        hue="peach"
                        aspect="aspect-[9/16]"
                        label="Watch on Instagram ↗"
                      />
                      <figcaption className="type-hand px-1 pt-1 text-base text-text-muted">
                        {reel.label}
                      </figcaption>
                    </figure>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </Reveal>
      </div>
    </section>
  );
}

// src/components/chapter-two/MusicSection.vue
<template>
  <section id="music" class="music">
    <div class="container">
      <SectionHeader
        note="keeping taal…"
        title="The Musician"
        highlight="Musician"
        hue="peach"
        :vis="vis"
      />

      <p class="music__body" :class="{ 'is-in': vis }">{{ music.body }}</p>

      <div class="music__cards" :class="{ 'is-in': vis }">
        <!-- Spotify artist -->
        <a :href="music.spotifyArtistUrl" target="_blank" rel="noopener" class="card">
          <Tape hue="leaf" :rotate="-6" />
          <img :src="music.artistImage" :alt="music.artistName" class="card__art" />
          <div>
            <span class="card__kicker mono-xs">Spotify artist</span>
            <h3>{{ music.artistName }}</h3>
            <p>{{ music.artistBio }}</p>
          </div>
        </a>

        <!-- YouTube channel -->
        <a :href="music.youtubeChannelUrl || 'https://www.youtube.com/@MusicalKirtiraj'" target="_blank" rel="noopener" class="card">
          <Tape hue="pink" :rotate="7" flip />
          <img :src="music.youtubeImage" :alt="music.youtubeName" class="card__art" />
          <div>
            <span class="card__kicker mono-xs">{{ music.youtubeStats }}</span>
            <h3>{{ music.youtubeName }}</h3>
            <p>{{ music.youtubeTagline }}</p>
          </div>
        </a>
      </div>

      <!-- Debut single -->
      <div class="debut" :class="{ 'is-in': vis }">
        <div class="debut__copy">
          <span class="debut__label hand">{{ music.debutLabel }}</span>
          <h3>{{ music.debutTitle }}</h3>
          <p>{{ music.debutStory }}</p>
          <a :href="music.spotifyTrackUrl" target="_blank" rel="noopener" class="debut__link hand">
            listen on Spotify ↗
          </a>
        </div>

        <div class="debut__player">
          <iframe
            :src="music.spotifyEmbedUrl"
            title="Spotify player — Invisible Available Replaceable"
            width="100%"
            height="152"
            frameborder="0"
            loading="lazy"
            allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"
          ></iframe>
        </div>
      </div>

      <!-- Tabla reels — link out; embeds would pull in Meta's script. -->
      <div class="reels" :class="{ 'is-in': vis }">
        <a
          v-for="(r, i) in music.reels"
          :key="r.id"
          :href="r.href"
          target="_blank"
          rel="noopener"
          class="reel"
          :style="{ '--tilt': `${i % 2 === 0 ? -1.6 : 1.8}deg`, '--d': `${i * 90}ms` }"
        >
          <Tape :hue="reelHues[i % reelHues.length]" :rotate="i % 2 === 0 ? -8 : 9" :flip="i % 2 === 1" />
          <span class="reel__icon" aria-hidden="true">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="m10 15 5-3-5-3z" /><rect width="20" height="20" x="2" y="2" rx="5" /></svg>
          </span>
          <span class="reel__label hand">{{ r.label }}</span>
        </a>
      </div>
    </div>
  </section>
</template>

<script setup lang="ts">
import { musicSection as music } from '../../content/novel';
import SectionHeader from './SectionHeader.vue';
import Tape from './Tape.vue';

defineProps<{ vis?: boolean }>();

const reelHues = ['blue', 'sun', 'leaf'];
</script>

<style scoped>
.music { padding: var(--sp-9) 0; }

.music__body,
.music__cards,
.debut,
.reels {
  opacity: 0;
  transform: translateY(26px);
  transition: opacity 720ms cubic-bezier(0.32, 0.72, 0, 1),
              transform 780ms cubic-bezier(0.32, 0.72, 0, 1);
}
.music__body.is-in,
.music__cards.is-in,
.debut.is-in,
.reels.is-in { opacity: 1; transform: none; }
.music__cards { transition-delay: 90ms; }
.debut { transition-delay: 170ms; }
.reels { transition-delay: 240ms; }

.music__body {
  max-width: 56ch;
  margin-top: var(--sp-6);
  font-family: var(--font-body);
  font-size: 1.05rem;
  line-height: 1.75;
  color: var(--text-muted);
}

.music__cards {
  display: grid;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  gap: var(--sp-6);
  margin-top: var(--sp-8);
}
@media (max-width: 760px) { .music__cards { grid-template-columns: minmax(0, 1fr); } }

.card {
  position: relative;
  display: flex;
  align-items: center;
  gap: var(--sp-4);
  padding: var(--sp-5);
  border: 1px solid var(--border);
  background: var(--surface-solid);
  border-radius: 3px;
  transition: transform 380ms cubic-bezier(0.34, 1.3, 0.64, 1), box-shadow 320ms var(--ease-out);
}
.card:nth-child(1) { transform: rotate(-1.2deg); }
.card:nth-child(2) { transform: rotate(1.4deg); }
.card:hover { transform: rotate(0deg) translateY(-4px); box-shadow: var(--shadow-card); }
.card__art {
  width: 72px; height: 72px;
  border-radius: 3px;
  object-fit: cover;
  flex-shrink: 0;
  border: 1px solid var(--border);
}
.card__kicker { display: block; color: var(--text-faint); margin-bottom: 3px; }
.card h3 {
  font-family: var(--font-body);
  font-size: 1rem;
  font-weight: 600;
  color: var(--text);
  text-transform: none;
  letter-spacing: 0;
}
.card p { font-size: 0.88rem; line-height: 1.55; color: var(--text-muted); margin-top: 3px; }

.debut {
  display: grid;
  grid-template-columns: minmax(0, 1fr) minmax(0, 0.95fr);
  gap: var(--sp-7);
  align-items: center;
  margin-top: var(--sp-8);
  padding-top: var(--sp-7);
  border-top: 1px solid var(--border);
}
@media (max-width: 860px) { .debut { grid-template-columns: minmax(0, 1fr); gap: var(--sp-5); } }

.debut__label { display: block; font-size: 1.35rem; color: var(--accent); }
.debut__copy h3 {
  font-family: var(--font-display);
  font-size: clamp(1.6rem, 3.4vw, 2.4rem);
  font-weight: 700;
  letter-spacing: -0.02em;
  text-transform: uppercase;
  color: var(--text);
  margin: var(--sp-2) 0 var(--sp-3);
}
.debut__copy p {
  font-family: var(--font-body);
  font-size: 0.98rem;
  line-height: 1.7;
  color: var(--text-muted);
  max-width: 52ch;
}
.debut__link {
  display: inline-block;
  margin-top: var(--sp-4);
  font-size: 1.25rem;
  color: var(--text);
  text-decoration: underline;
  text-decoration-color: var(--crayon-leaf);
  text-decoration-thickness: 2px;
  text-underline-offset: 6px;
}
.debut__link:hover { color: var(--text-muted); }
.debut__player iframe { border-radius: 12px; display: block; }

.reels {
  display: grid;
  grid-template-columns: repeat(3, minmax(0, 1fr));
  gap: var(--sp-5);
  margin-top: var(--sp-8);
}
@media (max-width: 640px) { .reels { grid-template-columns: minmax(0, 1fr); } }

.reel {
  position: relative;
  display: flex;
  align-items: center;
  gap: var(--sp-3);
  padding: var(--sp-5);
  border: 1px solid var(--border);
  background: var(--surface-solid);
  border-radius: 3px;
  transform: rotate(var(--tilt));
  transition: transform 380ms cubic-bezier(0.34, 1.3, 0.64, 1), box-shadow 320ms var(--ease-out);
}
.reel:hover { transform: rotate(0deg) translateY(-4px); box-shadow: var(--shadow-card); }
.reel__icon {
  display: grid;
  place-items: center;
  width: 34px; height: 34px;
  border-radius: 50%;
  background: var(--accent-glass);
  color: var(--accent);
  flex-shrink: 0;
}
.reel__icon svg { width: 17px; height: 17px; }
.reel__label { font-size: 1.2rem; color: var(--text); }

@media (prefers-reduced-motion: reduce) {
  .music__body, .music__cards, .debut, .reels { transform: none; transition: opacity 300ms ease; }
  .card, .reel { transition: none; }
}
</style>
